<a href="https://www.kaggle.com/code/samithsachidanandan/nifty-web-scrapping?scriptVersionId=221052722" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [8]:
!pip install --upgrade nselib

Requirement already satisfied: nselib in /usr/local/lib/python3.10/dist-packages (1.5)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from nselib) (2.32.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from nselib) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from nselib) (1.13.1)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->nselib) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->nselib) (2024.12.14)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas->nselib) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas->nselib) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas->nselib) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas->nselib) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas->nselib) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas->nselib) (2.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->nselib) (1.17.0)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.22.4->pandas->nselib) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.22.4->pandas->nselib) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy>=1.22.4->pandas->nselib) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy>=1.22.4->pandas->nselib) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy>=1.22.4->pandas->nselib) (2024.2.0)

In [9]:
import nselib
from nselib import capital_market

In [10]:
data = capital_market.index_data("NIFTY 50", from_date="05-02-2012", to_date="05-02-2025")

In [11]:
data.head()

,TIMESTAMP,INDEX_NAME,OPEN_INDEX_VAL,HIGH_INDEX_VAL,CLOSE_INDEX_VAL,LOW_INDEX_VAL,TRADED_QTY,TURN_OVER
0,01-01-2013,NIFTY 50,5937.65,5963.90,5950.85,5935.20,77902745,3298.74
1,02-01-2013,NIFTY 50,5982.60,6006.05,5993.25,5982.00,116057389,4992.90
2,03-01-2013,NIFTY 50,6015.80,6017.00,6009.50,5986.55,99989933,4883.13
3,04-01-2013,NIFTY 50,6011.95,6020.75,6016.15,5981.55,113232990,5191.38
4,07-01-2013,NIFTY 50,6042.15,6042.15,5988.40,5977.15,110248018,5093.62

In [12]:
# Save to CSV file with Date as the first column
data.to_csv("NIFTY50_Historical_Data.csv", index=True, index_label="Date")

print("Data saved successfully as 'NIFTY_Historical_Data.csv'")

Data saved successfully as 'NIFTY_Historical_Data.csv'